package entities;
// Generated 16-dic-2014 9:35:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsignaturaId generated by hbm2java
 */
@Embeddable
public class AsignaturaId  implements java.io.Serializable {


     private String codAsignatura;
     private String nombreUniversidad;

    public AsignaturaId() {
    }

    public AsignaturaId(String codAsignatura, String nombreUniversidad) {
       this.codAsignatura = codAsignatura;
       this.nombreUniversidad = nombreUniversidad;
    }
   


    @Column(name="codAsignatura", nullable=false)
    public String getCodAsignatura() {
        return this.codAsignatura;
    }
    
    public void setCodAsignatura(String codAsignatura) {
        this.codAsignatura = codAsignatura;
    }


    @Column(name="nombreUniversidad", nullable=false, length=200)
    public String getNombreUniversidad() {
        return this.nombreUniversidad;
    }
    
    public void setNombreUniversidad(String nombreUniversidad) {
        this.nombreUniversidad = nombreUniversidad;
    }


    @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsignaturaId) ) return false;
		 AsignaturaId castOther = ( AsignaturaId ) other; 
         
		 return (this.getCodAsignatura().equals(castOther.getCodAsignatura()))
 && ( (this.getNombreUniversidad().equals(castOther.getNombreUniversidad())) || ( this.getNombreUniversidad()!=null && castOther.getNombreUniversidad()!=null && this.getNombreUniversidad().equals(castOther.getNombreUniversidad()) ) );
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAsignatura() == null ? 0 : this.getCodAsignatura().hashCode() );
         result = 37 * result + ( getNombreUniversidad() == null ? 0 : this.getNombreUniversidad().hashCode() );
         return result;
   }   


}

