package entities;
// Generated 16-dic-2014 9:35:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="contrato"
    ,catalog="gestordb"
)
public class Contrato  implements java.io.Serializable {


     private Integer idContrato;
     private Movilidad movilidad;
     private Date fecha;
     private String estado;
     private byte[] archivo;
     private Set<Equivalencia> equivalencias = new HashSet<Equivalencia>(0);

    public Contrato() {
    }

    public Contrato(Movilidad movilidad, Date fecha, String estado, byte[] archivo, Set<Equivalencia> equivalencias) {
       this.movilidad = movilidad;
       this.fecha = fecha;
       this.estado = estado;
       this.archivo=archivo;
       this.equivalencias = equivalencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idContrato", unique=true, nullable=false)
    public Integer getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMovilidad")
    public Movilidad getMovilidad() {
        return this.movilidad;
    }
    
    public void setMovilidad(Movilidad movilidad) {
        this.movilidad = movilidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
     @Column(name="archivo")
    public byte[] getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="contrato_equivalencia", catalog="gestordb", joinColumns = { 
        @JoinColumn(name="idContrato", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idEquivalencia", nullable=false, updatable=false) })
    public Set<Equivalencia> getEquivalencias() {
        return this.equivalencias;
    }
    
    public void setEquivalencias(Set<Equivalencia> equivalencias) {
        this.equivalencias = equivalencias;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + Objects.hashCode(this.idContrato);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Contrato)) {
            return false;
        }
        final Contrato other = (Contrato) obj;
        if (!Objects.equals(this.idContrato, other.idContrato)) {
            return false;
        }
        return true;
    }




}

