package entities;
// Generated 09-mar-2015 20:16:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="gestordb"
)
public class Curso  implements java.io.Serializable {


     private String curso;

    public Curso() {
    }

    public Curso(String curso) {
       this.curso = curso;
    }
   
     @Id 

    
    @Column(name="curso", unique=true, nullable=false, length=15)
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }




}


