package entities;
// Generated 11-abr-2015 11:57:17 by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,catalog="gestordb"
)
public class Direccion  implements java.io.Serializable {


     private String direccion;
     private Configuracion configuracion;

    public Direccion() {
    }

    public Direccion(String direccion, Configuracion configuracion) {
       this.direccion = direccion;
       this.configuracion = configuracion;
    }
   
     @Id 

    
    @Column(name="direccion", unique=true, nullable=false, length=300)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="configuracion", nullable=false)
    public Configuracion getConfiguracion() {
        return this.configuracion;
    }
    
    public void setConfiguracion(Configuracion configuracion) {
        this.configuracion = configuracion;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 73 * hash + Objects.hashCode(this.direccion);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (obj instanceof Direccion==false) {
            
            return false;
        }
        final Direccion other = (Direccion) obj;
        if (!Objects.equals(this.direccion.toLowerCase(), other.direccion.toLowerCase())) {
            
            return false;
        }
        
        return true;
    }




}


