package entities;
// Generated 11-mar-2015 20:12:21 by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name="idioma"
    ,catalog="gestordb"
)
public class Idioma  implements java.io.Serializable {


     private String idioma;

    public Idioma() {
    }

    public Idioma(String idioma) {
       this.idioma = idioma;
    }
   
     @Id 

    
    @Column(name="idioma", unique=true, nullable=false, length=40)
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + Objects.hashCode(this.idioma);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Idioma other = (Idioma) obj;
        if (!Objects.equals(this.idioma, other.idioma)) {
            return false;
        }
        return true;
    }




}


