package entities;
// Generated 16-dic-2014 9:35:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MiembroGrupoAsignaturaA generated by hbm2java
 */
@Entity
@Table(name="miembro_grupo_asignatura_a"
    ,catalog="gestordb"
)
public class MiembroGrupoAsignaturaA  implements java.io.Serializable {


     private Integer idmiembroGrupoAsignaturaA;
     private Asignatura asignatura;
     private Equivalencia equivalencia;

    public MiembroGrupoAsignaturaA() {
    }

    public MiembroGrupoAsignaturaA(Asignatura asignatura, Equivalencia equivalencia) {
       this.asignatura = asignatura;
       this.equivalencia = equivalencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmiembro_grupo_asignatura_a", unique=true, nullable=false)
    public Integer getIdmiembroGrupoAsignaturaA() {
        return this.idmiembroGrupoAsignaturaA;
    }
    
    public void setIdmiembroGrupoAsignaturaA(Integer idmiembroGrupoAsignaturaA) {
        this.idmiembroGrupoAsignaturaA = idmiembroGrupoAsignaturaA;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="codAsignatura", referencedColumnName="codAsignatura"), 
        @JoinColumn(name="nombreUniversidad", referencedColumnName="nombreUniversidad") } )
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEquivalencia")
    public Equivalencia getEquivalencia() {
        return this.equivalencia;
    }
    
    public void setEquivalencia(Equivalencia equivalencia) {
        this.equivalencia = equivalencia;
    }




}


